### ISSUE TITLE
Semantic action type names

### ISSUE THREAD

**Issue by Ralith** [LPGhatguy/keybee#3]
Action type names should reflect the meaning of the action, not the mechanism used to trigger it (which may vary). For example, `ButtonAction` and `ButtonHeldAction` might be more descriptively named `EventAction` and `BooleanAction` to reflect their behavior rather than one possible input device. This should preempt confusion about e.g. why `ButtonAction` might yield `false` while a button is pressed.

**Comment by LPGhatguy** [comment]
This was fixed at some point, with `EventAction` and `BoolAction` both in the codebase for some time!
